config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/details_show'
  get 'home/second_page'
  get 'home/third_page'
  get 'home/fourth_page'
  get 'search', to: 'home#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/anime_list.rb
#https://kitsu.io/api/edge/anime

require 'httparty'
#class AnimeList < ApplicationRecord
class AnimeList 
    include HTTParty
    base_uri 'https://kitsu.io/api/edge'

    
    def get_anime
        self.class.get('/anime/?page[limit]=20')
    end

    def all_anime_json
        get_anime.parsed_response
    end

    def get_first_page 
        self.class.get('/anime/?page%5Blimit%5D=10&page%5Boffset%5D=0')
    end

    def first_page_json
        get_first_page.parsed_response
    end

    def get_second_page 
        self.class.get('/anime/?page%5Blimit%5D=10&page%5Boffset%5D=10')
    end

    def second_page_json
        get_second_page.parsed_response
    end

    def get_third_page 
        self.class.get('/anime/?page[limit]=10&page[offset]=20')
    end

    def third_page_json
        get_third_page.parsed_response
    end

    def get_fourth_page 
        self.class.get('/anime/?page[limit]=10&page[offset]=30')
    end

    def fourth_page_json
        get_fourth_page.parsed_response
    end

    def get_specific_details_json
        get_specific_details.parsed_response
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HTTParty
 
  def index
    @all_anime = AnimeList.new.first_page_json["data"]    
  end



  # GET details of each selected anime in list
  def details_show
    @specific_anime = HTTParty.get("https://kitsu.io/api/edge/anime/#{
    params[:id]
    }").parsed_response["data"]

    @specific_genre = HTTParty.get("https://kitsu.io/api/edge/anime/#{
      params[:id]
      }/genres").parsed_response["data"]

    @specific_review = HTTParty.get("https://kitsu.io/api/edge/anime/#{
      params[:id]
      }/reviews").parsed_response["data"]

    # @review_user = HTTParty.get("https://kitsu.io/api/edge/reviews/#{
    #   params[:@specific_review["id"]]
    #   }/user").parsed_response["data"]
  end 

  def second_page
    @all_anime2 = AnimeList.new.second_page_json["data"]
  end

  def third_page
    @all_anime3 = AnimeList.new.third_page_json["data"]
  end

  def fourth_page
    @all_anime4 = AnimeList.new.fourth_page_json["data"]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def main_title(separator = " | ")
        [content_for(:title), 'AnimeRuby'].compact.join(separator)
      end
      
      def selected_anime_page_title(title)
        content_for(:title){ title }
        content_tag(:h1, title)
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_anime_body.html.erb
<h1 class="d-flex align-items-center justify-content-center">Anime</h1>

 <% @all_anime.each do |anime| %>
      <div class="container my-5" style="min-height: 1000px;">
            <div class="container">
                <div class="card mb-3" >
                    <div class="row g-0">
                        <div class="col-md-2">
                            <%= image_tag anime["attributes"]["posterImage"]["original"] , class: "rounded-start", 
                            style: "height: 300px; width: 200px;"%>
                        </div>
                        <div class="col-md-10">
                            <div class="container">
                                <div class="card-body">
                                    <h5 class="card-title"><%= anime["attributes"]["titles"]["en_jp"] %></h5>
                                    <p class="badge text-bg-success"><%= anime["attributes"]["status"] %></p>
                                    <p class="card-text"><%= anime["attributes"]["synopsis"].truncate_words(40) %></p>
                                    <p class="card-text">
                                        <span class="badge text-bg-primary mr-2"><%= anime["attributes"]["ageRating"] %></span>
                                        <span class="badge text-bg-secondary"><%= anime["attributes"]["subtype"] %></span>
                                    </p>
                                    <div class="d-flex justify-content-end">
                                        <%= link_to "View More", root_path, class: "btn btn-info" %>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    <% end %>
    <div class="container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                <li class="page-item">
                    <%= link_to "Next", second_page_path , class: "page-link" %>
                </li>
            </ul>
        </nav>
    </div>

app/views/home/_footer.html.erb
<footer class="footer  py-2 bg-light">
    <div class="container">
        <p>Footer is here</p>
    </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light fixed-top">
  <div class="container-fluid">
    <%= link_to "myAnime", root_path, class: "navbar-brand fw-bolder" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
      </ul>
       <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/details_show.html.erb
<%
=begin%>
 <% content_for :title do 'Animeruby | ' + @specific_anime["attributes"]["titles"]["en_jp"] %>
<% end %> 
<%
=end%>

<%= selected_anime_page_title @specific_anime["attributes"]["titles"]["en_jp"] %>

 <% if @specific_anime["attributes"]["coverImage"].blank? %>
    <div  style= "height: 240px; width: 100%; background-color: grey" , class= "mt-5"></div>
<% else %>
    <%= image_tag @specific_anime["attributes"]["coverImage"]["large"], 
        style: "height: 240px; width: 100%;" , class: "mt-5"%>
<% end %>



<h4 class="d-flex align-items-center justify-content-center my-3">
    <%= @specific_anime["attributes"]["titles"]["en_jp"] %>
</h4>

<div class="container", style="min-height: 22rem">
    <div class="row">
        <div class="col-md-3">
            <p class="fw-bold">Description:</p>
        </div>
        <div class="col-md-9">
            <p class="fw-normal fs-10">
                <%= @specific_anime["attributes"]["description"] %>
            </p>
        </div>
    </div>
     <div class="row">
        <div class="col-md-3">
            <p class="fw-bold">Duration:</p>
        </div>
        <div class="col-md-9">
            <p class="fw-normal fs-10">
                <%= @specific_anime["attributes"]["startDate"].to_time.strftime("%B %d, %Y") %> to 
                <% if @specific_anime["attributes"]["endDate"].blank? %>
                    <span class="fw-bold">N/A</span>
                <% else %>
                   <%= @specific_anime["attributes"]["endDate"].to_time.strftime("%B %d, %Y") %>
                <% end %>
            </p>
        </div>
    </div>
     <div class="row">
        <div class="col-md-3">
            <p class="fw-bold">Ratings:</p>
        </div>
        <div class="col-md-9">
            <p class="fw-normal fs-10">
                <span class="badge text-bg-secondary"><%=  @specific_anime["attributes"]["subtype"].upcase %></span>
                <span class="badge text-bg-primary mr-2"><%=  "#{@specific_anime["attributes"]["ageRating"]} (#{@specific_anime["attributes"]["ageRatingGuide"]})" %></span>
                <span class="badge text-bg-warning"><%=  @specific_anime["attributes"]["status"].capitalize %></span>
            </p>
        </div>
    </div>
     <div class="row">
        <div class="col-md-3">
            <p class="fw-bold">No of Episodes:</p>
        </div>
        <div class="col-md-9">
            <p class="fw-normal fs-10">
                <% if @specific_anime["attributes"]["episodeCount"].blank? %>
                    <span class="badge text-bg-success">N/A</span>
                <% else %>
                   <span class="badge text-bg-success"><%=  @specific_anime["attributes"]["episodeCount"] %></span>
                <% end %>
                
            </p>
        </div>
     </div>
     <div class="row">
        <div class="col-md-3">
            <p class="fw-bold">Genres:</p>
        </div>
        <div class="col-md-9"> 
            <% @specific_genre.each do |genre| %>
                <span class="badge rounded-pill text-bg-light mr-2">
                    <%= genre["attributes"]["name"] %>
                </span>
            <% end %>
        </div>
     </div>
</div>

<div class="container">
    <div class="card border-light my-3" style="max-width: 100%">
        <div class="card-header d-flex align-items-center justify-content-center">
            <h5>Reviews</h5>
        </div>
        <div class="card-body text-dark">
            <% @specific_review.each_with_index do |review, index|%>
                <p>
                    <a class="btn btn-outline-primary" data-bs-toggle="collapse" 
                        href="#Example<%= review["id"] %>"  role="button" aria-expanded="false" 
                        aria-controls="#Example<%= review["id"] %>">
                        Review : <%= index + 1 %>
                    </a>
                </p>
                <div class="collapse" id="Example<%= review["id"] %>">
                    <div class="card card-body mb-3">
                        <div class = "row g-0">
                            <div class="col-md-2"> 
                                <% if HTTParty.get("https://kitsu.io/api/edge/reviews/#{review["id"]}/user")
                                    .parsed_response["data"]["attributes"]["avatar"].blank? %>
                                    <div class="bg-secondary" style="width: 3rem; height: 3rem; border-radius: 50%"></div>
                                <% else %>
                                    <%= image_tag HTTParty.get("https://kitsu.io/api/edge/reviews/#{review["id"]}/user")
                                    .parsed_response["data"]["attributes"]["avatar"]["medium"], 
                                    style: "height: 100px; width: 100px;" , class: "mt-1 rounded-circle border-info"%>
                                <% end %>                           
                                <p class="fw-bold d-flex align-items-center justify-content-start">
                                    <%= HTTParty.get("https://kitsu.io/api/edge/reviews/#{review["id"]}/user")
                                    .parsed_response["data"]["attributes"]["name"]%></p>
                                <p class = "text-danger">
                                   <%= review["attributes"]["likesCount"].to_s %> 
                                    <i class="fa-solid fa-heart"></i>
                                </p>
                            </div>
                            <div class="col-md-9"> 
                                <p><%= review["attributes"]["content"] %></p>      
                            </div>  
                        </div>
                                        
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/home/fourth_page.html.erb
 <div style="min-height: 800px" class="mt-5 mb-5">
 <h1 class="d-flex align-items-center justify-content-center">Anime</h1>
 <% @all_anime4.each do |anime| %>
      <div class="container">
            <div class="container">
                <div class="card mb-3" >
                    <div class="row g-0">
                        <div class="col-md-2">
                            <%= image_tag anime["attributes"]["posterImage"]["original"] , class: "rounded-start", 
                            style: "height: 300px; width: 200px;"%>
                        </div>
                        <div class="col-md-10">
                            <div class="container">
                                <div class="card-body">
                                    <h5 class="card-title"><%= anime["attributes"]["titles"]["en_jp"] %></h5>
                                    <p class="badge text-bg-success"><%= anime["attributes"]["status"] %></p>
                                    <p class="card-text"><%= anime["attributes"]["synopsis"].truncate_words(40) %></p>
                                    <p class="card-text">
                                        <span class="badge text-bg-primary mr-2"><%= anime["attributes"]["ageRating"] %></span>
                                        <span class="badge text-bg-secondary"><%= anime["attributes"]["subtype"] %></span>
                                    </p>
                                      <div class="d-flex justify-content-end">
                                        <%= link_to "View More", {:controller => "home", :action => "details_show", :id => anime["id"] }, class: "btn btn-info" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    <% end %>
    <div class="container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end pb-4">
                <li class="page-item">
                    <%= link_to "Previous", home_third_page_path , class: "page-link" %>
                </li>
                <li class="page-item">
                    <%= link_to "Next", home_fourth_page_path , class: "page-link" %>
                </li>
            </ul>
        </nav>
    </div>

    </div>

app/views/home/index.html.erb
 <div style="min-height: 800px" class="mt-5 mb-5">
 <h1 class="d-flex align-items-center justify-content-center">Anime</h1>
 <% @all_anime.each do |anime| %>
      <div class="container">
            <div class="container">
                <div class="card mb-3" >
                    <div class="row g-0">
                        <div class="col-md-2">
                            <%= image_tag anime["attributes"]["posterImage"]["original"] , class: "rounded-start", 
                            style: "height: 300px; width: 200px;"%>
                        </div>
                        <div class="col-md-10">
                            <div class="container">
                                <div class="card-body">
                                    <h5 class="card-title"><%= anime["attributes"]["titles"]["en_jp"] %></h5>
                                    <p class="badge text-bg-success"><%= anime["attributes"]["status"] %></p>
                                    <p class="card-text"><%= anime["attributes"]["synopsis"].truncate_words(40) %></p>
                                    <p class="card-text">
                                        <span class="badge text-bg-primary mr-2"><%= anime["attributes"]["ageRating"] %></span>
                                        <span class="badge text-bg-secondary"><%= anime["attributes"]["subtype"] %></span>
                                    </p>
                                      <div class="d-flex justify-content-end">
                                        <%= link_to "View More", {:controller => "home", :action => "details_show", :id => anime["id"] }, class: "btn btn-info" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
      </div>
 <% end %>
    <div class="container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end pb-4">
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                <li class="page-item">
                    <%= link_to "Next", home_second_page_path , class: "page-link" %>
                </li>
            </ul>
        </nav>
    </div>

    </div>

app/views/home/search.html.erb
<div style="min-height: 800px" class="mt-5 mb-5">
    <h1>Search Results</h1>
    <%
=begin%>
 <%= render @result_anime  %> 
<%
=end%>
</div>

app/views/home/second_page.html.erb
 <div style="min-height: 800px" class="mt-5 mb-5">
 <h1 class="d-flex align-items-center justify-content-center">Anime</h1>
 <% @all_anime2.each do |anime| %>
      <div class="container">
            <div class="container">
                <div class="card mb-3" >
                    <div class="row g-0">
                        <div class="col-md-2">
                            <%= image_tag anime["attributes"]["posterImage"]["original"] , class: "rounded-start", 
                            style: "height: 300px; width: 200px;"%>
                        </div>
                        <div class="col-md-10">
                            <div class="container">
                                <div class="card-body">
                                    <h5 class="card-title"><%= anime["attributes"]["titles"]["en_jp"] %></h5>
                                    <p class="badge text-bg-success"><%= anime["attributes"]["status"] %></p>
                                    <p class="card-text"><%= anime["attributes"]["synopsis"].truncate_words(40) %></p>
                                    <p class="card-text">
                                        <span class="badge text-bg-primary mr-2"><%= anime["attributes"]["ageRating"] %></span>
                                        <span class="badge text-bg-secondary"><%= anime["attributes"]["subtype"] %></span>
                                    </p>
                                      <div class="d-flex justify-content-end">
                                        <%= link_to "View More", {:controller => "home", :action => "details_show", :id => anime["id"] }, class: "btn btn-info" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    <% end %>
    <div class="container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end pb-4">
                <li class="page-item">
                    <%= link_to "Previous", root_path , class: "page-link" %>
                </li>
                <li class="page-item">
                    <%= link_to "Next", home_third_page_path , class: "page-link" %>
                </li>
            </ul>
        </nav>
    </div>

    </div>

app/views/home/third_page.html.erb
 <div style="min-height: 800px" class="mt-5 mb-5">
 <h1 class="d-flex align-items-center justify-content-center">Anime</h1>
 <% @all_anime3.each do |anime| %>
      <div class="container">
            <div class="container">
                <div class="card mb-3" >
                    <div class="row g-0">
                        <div class="col-md-2">
                            <%= image_tag anime["attributes"]["posterImage"]["original"] , class: "rounded-start", 
                            style: "height: 300px; width: 200px;"%>
                        </div>
                        <div class="col-md-10">
                            <div class="container">
                                <div class="card-body">
                                    <h5 class="card-title"><%= anime["attributes"]["titles"]["en_jp"] %></h5>
                                    <p class="badge text-bg-success"><%= anime["attributes"]["status"] %></p>
                                    <p class="card-text"><%= anime["attributes"]["synopsis"].truncate_words(40) %></p>
                                    <p class="card-text">
                                        <span class="badge text-bg-primary mr-2"><%= anime["attributes"]["ageRating"] %></span>
                                        <span class="badge text-bg-secondary"><%= anime["attributes"]["subtype"] %></span>
                                    </p>
                                      <div class="d-flex justify-content-end">
                                        <%= link_to "View More", {:controller => "home", :action => "details_show", :id => anime["id"] }, class: "btn btn-info" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    <% end %>
    <div class="container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end pb-4">
                <li class="page-item">
                    <%= link_to "Previous", home_second_page_path , class: "page-link" %>
                </li>
                <li class="page-item">
                    <%= link_to "Next", home_fourth_page_path , class: "page-link" %>
                </li>
            </ul>
        </nav>
    </div>

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= main_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/fontawesome.css" integrity="sha384-X8QTME3FCg1DLb58++lPvsjbQoCT9bp3MsUU3grbIny/3ZwUJkRNO8NPW6zqzuW9" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v6.1.2/js/all.js" integrity="sha384-11X1bEJVFeFtn94r1jlvSC7tlJkV2VJctorjswdLzqOJ6ZvYBSZQkaQVXG0R4Flt" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "home/header" %>
    <%= yield %>
    <%= render "home/footer" %>
  </body>
</html>